/**
 * @fileoverview gRPC-Web generated client stub for sensor
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.6.1
// source: proto/sensor.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.sensor = require('./sensor_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.sensor.SensorClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.sensor.SensorPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sensor.SensorRequest,
 *   !proto.sensor.SensorResponse>}
 */
const methodDescriptor_Sensor_TempSensor = new grpc.web.MethodDescriptor(
  '/sensor.Sensor/TempSensor',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.sensor.SensorRequest,
  proto.sensor.SensorResponse,
  /**
   * @param {!proto.sensor.SensorRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sensor.SensorResponse.deserializeBinary
);


/**
 * @param {!proto.sensor.SensorRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.sensor.SensorResponse>}
 *     The XHR Node Readable Stream
 */
proto.sensor.SensorClient.prototype.tempSensor =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/sensor.Sensor/TempSensor',
      request,
      metadata || {},
      methodDescriptor_Sensor_TempSensor);
};


/**
 * @param {!proto.sensor.SensorRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.sensor.SensorResponse>}
 *     The XHR Node Readable Stream
 */
proto.sensor.SensorPromiseClient.prototype.tempSensor =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/sensor.Sensor/TempSensor',
      request,
      metadata || {},
      methodDescriptor_Sensor_TempSensor);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sensor.SensorRequest,
 *   !proto.sensor.SensorResponse>}
 */
const methodDescriptor_Sensor_HumiditySensor = new grpc.web.MethodDescriptor(
  '/sensor.Sensor/HumiditySensor',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.sensor.SensorRequest,
  proto.sensor.SensorResponse,
  /**
   * @param {!proto.sensor.SensorRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sensor.SensorResponse.deserializeBinary
);


/**
 * @param {!proto.sensor.SensorRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.sensor.SensorResponse>}
 *     The XHR Node Readable Stream
 */
proto.sensor.SensorClient.prototype.humiditySensor =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/sensor.Sensor/HumiditySensor',
      request,
      metadata || {},
      methodDescriptor_Sensor_HumiditySensor);
};


/**
 * @param {!proto.sensor.SensorRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.sensor.SensorResponse>}
 *     The XHR Node Readable Stream
 */
proto.sensor.SensorPromiseClient.prototype.humiditySensor =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/sensor.Sensor/HumiditySensor',
      request,
      metadata || {},
      methodDescriptor_Sensor_HumiditySensor);
};


module.exports = proto.sensor;

