/**
 * @fileoverview gRPC-Web generated client stub for charts
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.6.1
// source: proto/chart.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.charts = require('./chart_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.charts.ChartDataServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.charts.ChartDataServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.charts.LineChartRequest,
 *   !proto.charts.LineChartResponse>}
 */
const methodDescriptor_ChartDataService_GetLineChartData = new grpc.web.MethodDescriptor(
  '/charts.ChartDataService/GetLineChartData',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.charts.LineChartRequest,
  proto.charts.LineChartResponse,
  /**
   * @param {!proto.charts.LineChartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.charts.LineChartResponse.deserializeBinary
);


/**
 * @param {!proto.charts.LineChartRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.charts.LineChartResponse>}
 *     The XHR Node Readable Stream
 */
proto.charts.ChartDataServiceClient.prototype.getLineChartData =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/charts.ChartDataService/GetLineChartData',
      request,
      metadata || {},
      methodDescriptor_ChartDataService_GetLineChartData);
};


/**
 * @param {!proto.charts.LineChartRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.charts.LineChartResponse>}
 *     The XHR Node Readable Stream
 */
proto.charts.ChartDataServicePromiseClient.prototype.getLineChartData =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/charts.ChartDataService/GetLineChartData',
      request,
      metadata || {},
      methodDescriptor_ChartDataService_GetLineChartData);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.charts.ProgressChartRequest,
 *   !proto.charts.ProgressChartResponse>}
 */
const methodDescriptor_ChartDataService_GetProgressChartData = new grpc.web.MethodDescriptor(
  '/charts.ChartDataService/GetProgressChartData',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.charts.ProgressChartRequest,
  proto.charts.ProgressChartResponse,
  /**
   * @param {!proto.charts.ProgressChartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.charts.ProgressChartResponse.deserializeBinary
);


/**
 * @param {!proto.charts.ProgressChartRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.charts.ProgressChartResponse>}
 *     The XHR Node Readable Stream
 */
proto.charts.ChartDataServiceClient.prototype.getProgressChartData =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/charts.ChartDataService/GetProgressChartData',
      request,
      metadata || {},
      methodDescriptor_ChartDataService_GetProgressChartData);
};


/**
 * @param {!proto.charts.ProgressChartRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.charts.ProgressChartResponse>}
 *     The XHR Node Readable Stream
 */
proto.charts.ChartDataServicePromiseClient.prototype.getProgressChartData =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/charts.ChartDataService/GetProgressChartData',
      request,
      metadata || {},
      methodDescriptor_ChartDataService_GetProgressChartData);
};


module.exports = proto.charts;

