import Head from "next/head";
import { fetchData } from "../helpers/graph";
import ReactECharts from 'echarts-for-react';

export default function Home() {
  const options = {
    grid: { top: 8, right: 8, bottom: 24, left: 36 },
    xAxis: {
      type: 'category',
      data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    },
    yAxis: {
      type: 'value',
    },
    series: [
      {
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        smooth: true,
      },
      {
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'bar',
        smooth: true,
      },
    ],
    tooltip: {
      trigger: 'axis',
    },
    color:["#FF0000","#00FF00"]
  };
  return (
    <>
      <Head>
        <title>Chart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Hello World</h1>
          <ReactECharts option={options} />
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {

  const val = await fetchData()

  return {
    props: {
      data:val,
    },
  };
}
